/**
 * @file: This file consists of all static Ids used in the My Opportunity application
 * @class
 * @public
 * @author Abhishek Pant
 * @since 27 July 2017
 * @extends
 * @name com.amat.crm.opportunity.util.IdHelper
 * -------------------------------------------------------------------------------*
 * Modifications.                                                                 *
 * -------------                                                                  *
 * Ver.No    Date        Author    PCR No.           Description of change        *
 * ------ ---------- ------------ ----------  ------------------------------------*
 * V00    20/02/2018    Abhishek   PCR017480         Initial version              *
 *                      Pant       
 *                      (X089025)                                                 *
 *  Date           Author          PCR No.           Description of change        *
 * ------ ---------- ------------ ----------  ------------------------------------*
 * 19/07/2018      Abhishek        PCR018375         PSR/CBC Workflow Rejection   *
 *                 Pant                              (restart) Capability         *
 * 20/08/2018      Abhishek        PCR019492         ASC606 UI Changes            *
 *                 Pant                                                           *
 * 18/12/2018      Abhishek        PCR021481         Q2C Q1/Q2 enhancements       *
 *                 Pant                                                           *
 * 25/02/2019      Abhishek        PCR022669         Q2C Q2 UI Changes            *
 *                 Pant                                                           *
 * 17/06/2019      Abhishek        PCR023905         Migrate ESA/IDS db from Lotus*
 *                 Pant                              Notes to SAP Fiori Q2C       *
 *                                                   Application                  *
 * 26/09/2019      Abhishek        PCR025717         Q2C Q4 2019 Enhancements     *
 *                 Pant                                                           *
 * 07/01/2020      Arun            PCR026551         Pre-Shipment development     *
 *                 Jacob                                                          *
 * 29/04/2020      Arun            PCR028711         Q2C Enhancements for Q2-20   *
 *                 Jacob                                                          *
 * 25/11/2019      Abhishek        PCR026243         DL:1803 Display Migration to *
 *                 Pant                              Q2C                          *
 * 25/01/2021      Abhishek Pant   PCR033306         Q2C Display Enhancements     *
 * 06/04/2021     Arun Jacob      PCR034716          Q2C ESA,PSR Enhancements     *
***********************************************************************************
 */

jQuery.sap.declare("com.amat.crm.opportunity.util.IdHelper");

com.amat.crm.opportunity.Ids = {
		
		/************Advance Search************/
		FILTER_PANEL : "idS1_OPP_FILTER_PANEL",
		FILTER_BTN : "idS1_filter",
		FILTER_SFORM: "idS1_Filter_SForm",
		/******Start Of PCR022669: Q2C Q2 UI Changes*****/
		FILTER_HDR_RALL_BTN: "idS1_HDRRALLBTN",
		/******End Of PCR022669: Q2C Q2 UI Changes*****/
		FILTER_HDR_PSRBTN : "idS1_HDRPSRBTN",
		FILTER_HDR_PDCBTN : "idS1_HDRPDCBTN",
		FILTER_HDR_CBCBTN : "idS1_HDRCBCBTN",
		CUSTOMER_SEARCH : "idS1_OPP_IP_CUST",
		OPPORTUNITY_SEARCH :"idS1_OPP_IP_OPP",
		AMAT_QUOTE_NO_SEARCH : "idS1_OPP_IP_QTENO",
		SALES_ORDER_NO_SEARCH : "idS1_OPP_IP_ODRNO",
		SLOT_ID_SEARCH : "idS1_OPP_IP_SLID",
		LARGE_ORDER_SEARCH : "idS1_OPP_IP_LOW",
		CUSTOMER_PO_SEARCH : "idS1_OPP_IP_CustPO",
		VC_PRDDIS_SEARCH : "idS1_OPP_IP_VCPRDDIS",
		PSR_STAT_SEARCH : "idS1_OPP_IP_PSRSTAT",
		PDC_STAT_SEARCH : "idS1_OPP_IP_PDCSTAT",
		CBC_STAT_SEARCH : "idS1_OPP_IP_CBCSTAT",
		PSR_TYPE_SEARCH : "idS1_OPP_IP_PSRTYP",
		CBC_VERSION_SEARCH : "idS1_OPP_IP_CBCVER",
		
		/***************Start Of PCR019492: ASC606 UI Changes********/
		RRASDA_LVL_SEARCH : "idS1_OPP_IP_RRALVL",
		BU_SEARCH : "idS1_OPP_IP_BU",
		BOOK_QTR_SEARCH : "idS1_OPP_IP_BQTR",
		S2PSREVAL_RDBTN : "idS2_PSREVALRdBtn",
		S2PDCEVAL_RDBTN : "idS2_PDCEVALRdBtn",
		S2PDCAMJD_RDBTN : "idS2_PDCAMJDRdBtn",
		S2PSR_RRAREQTab : "idRRAReqTable",
		S2PSR_BSDAMTLVL : "idBSDAMTLVL",
		S2PSR_CNGHISPNL : "id_Psr_Chng_Hist",
		S2PSR_CNGHISTAB : "idPSRCmtHist",
		S2PSR_SSDAMTLVL : "idPSR_SSDAMTLVL",
		S2PSR_OLDSDAVAL : "idPSR_OLDSDAVAL",
		S2PSR_OLDSDALBL : "idPSR_OLDSDALBL",
		S2PSR_RRADEFFNOTE : "idPSR_RRADEFFNOTE",                                                                 //PCR019492++ 10257
		S2PSR_RELSPECINSTLDAYS : "S2_PSRSDA_TX_RelPerSpecInsDays", 
		S2PSR_RELSPECINSTLDAYSHB : "S2_PSRSDA_HX_RelPerSpecInsDays",
		S2PDC_RRAREQTab : "idPDCRRAReqTable",
		S2PDC_BSDAMTLVL : "idPDCBSDAMTLVL",
		S2PDC_CNGHISPNL : "id_Pdc_Chng_Hist",
		S2PDC_CNGHISTAB : "idPDCCmtHist",
		S2PDC_SSDAMTLVL : "idPDC_SSDAMTLVL",
		S2PDC_OLDSDAVAL : "idPDC_OLDSDAVAL",
		S2PDC_OLDSDALBL : "idPDC_OLDSDALBL",
		S2PDC_RRADEFFNOTE : "idPDC_RRADEFFNOTE",                                                                 //PCR019492++ 10257
		S2PSR_HDRMAINTXT : "idPSRText",
		S2PDC_HDRMAINTXT : "idPDCText",
		S2PSRDC_BMOSELLBLTXT : "idPSR_BMOSELRRALBL",
		S2PSRDC_BMOSELRRAVAL : "idPSR_BMOSELRRAVAL",
		S2PDC_BMOSELLBLTXT : "idPDC_BMOSELRRALBL",
		S2PDC_BMOSELRRAVAL : "idPDC_BMOSELRRAVAL",
		
		OPPORTUNITY_LIST_TMP_OPPBU_COLUMN : "idS1_OPPPBUCOLUMN2",
		OPPORTUNITY_LIST_TMP_PRODLN_COLUMN : "idS1_OPPPPRODLINECOLUMN2",
		OPPORTUNITY_LIST_TMP_PRODUCT_COLUMN : "idS1_OPPPPRODCTCOLUMN2",
		OPPORTUNITY_LIST_TMP_ITEMCAT_COLUMN : "idS1_OPPITMCATCOLUMN2",
		OPPORTUNITY_LIST_TMP_SDALBL_COLUMN : "idS1_OPPPSDALBLCOLUMN2",
		OPPORTUNITY_LIST_TMP_BOOKQTR_COLUMN : "idS1_OPPPBOOKQCOLUMN2",
		/***************End Of PCR019492: ASC606 UI Changes********/
		
		//***********Start Of PCR023905: Migrate ESA/IDS db from Lotus Notes to SAP Fiori Q2C App**************
		FILTER_HDR_ESABTN: "idS1_HDRRESABTN",
		OPPORTUNITY_LIST_TMP_ESASTAT_COLUMN : "idS1_OPPESASTATCOLUMN2",
		OPPORTUNITY_LIST_TMP_ESACURRSTAT_COLUMN : "idS1_OPPESACURRSTATCOLUMN2",
		OPPORTUNITY_LIST_ESASTAT_COLUMN : "idS1_OPPESASTATCOLUMN",
		OPPORTUNITY_LIST_ESACURRSTAT_COLUMN : "idS1_OPPESACURRSTATCOLUMN",
		ESA_STAT_SEARCH : "idS1_OPP_IP_ESASTAT",
		ICON_TABF_ESA : "idS2_IcnF_ESA",
		S2FTER_BTN_ESACANCEL : "idS2_Ftr_btnESACancel",
		S2FTER_BTN_ESARESET : "idS2_Ftr_btnESAReset",
		S2ESA_PANL_MAIN_COMMENT_PANEL: "idEsaMCommentPnl",
		S2ESA_PANL_MAIN_COMMENT_TEXT_AREA : "idEsaMainComtTxtArea",
		S2ESA_PANL_MAIN_COMMENT_SAVEBTN : "idS2EsaMainComSaveBtn",
		S2ESA_PANL_MAIN_COMMENT_COMMTABLE : "idEsaMainCommTab",
		S2ESAINFOTABMALBL : "IdS2EsaTAMBALbl",
		S2ESAINFOMASAGRRD : "idS2ESA_MasAgrRbg",
		S2ESAINFOMASAGRLBL : "IdS2EsaMasAgrLbl",
		S2ESAINFOCTAVPARD : "idS2ESA_CTAVPARbg",
		S2ESAINFOCTAVPALBL : "IdS2EsaCTAVPALbl",
		S2ESAINFOCTAVPATXT : "IdS2EsaCTAVPATxt",
		S2ESAESABTN : "idEsaEditBtn",
		S2ESARFTERD : "idEasRfeRdBtnGrp",
		S2ESAEQUIPTYPDEFRD : "idEasEquipTypeRdBtnGrp",
		S2ESAEQUIPSELLRD : "idEasEquipSel1RdBtnGrp",
		S2ESAASPECRD : "idEasASpecRdBtnGrp",
		S2ESASEVALRD : "idEasSEvalRdBtnGrp",
		S2ESASEVAL2RD : "idEasSEval2RdBtnGrp",
		S2ESAPRCURRRD : "idEasPrCurrRdBtnGrp",
		S2ESAOUTSHIPCSTRD : "idEasOutbndShipCstRdBtnGrp",
		S2ESAEQUIPRTNRD : "idEasEqupRtnRdBtnGrp",
		S2ESAPTSTRMRD : "idEasPTStndTermRdBtnGrp",
		S2ESAPTEXPTRD : "idEasPTExceptRdBtnGrp",
		S2ESACHINCONRD : "idEasChinConRdBtnGrp",
		S2ESAROLRD : "idEasROLRdBtnGrp",
		S2ESASHPTRMRD : "idEasShpTrmRdBtnGrp",
		S2ESASPSHPCONRD : "idEasSpShipConRdBtnGrp",
		S2ESARFEOTHIP: "idS2ESA_ResForEvalOthIP",
		S2ESAEQUIPTYPIPBX : "idEsa_EquipTypeIpBox",
		S2ESAEQUIPSEL1PRIP : "idS2ESA_EqipSel1PRIP",
		S2ESAEVAL1TSNDACAGREIP : "idS2ESA_EvalTsNDACAgreeIP",
		S2ESAEVAL1TSNDACAGREDP : "idS2ESA_EvalTsNDACAgreeDP",
		S2ESASEVAL2RDBX : "idEas_SEval2RdBox",
		S2ESAEQUIPRETNOTHIP : "idS2ESA_EquipRetnOthIP",
		S2ESAPAYTRMPTCDEIP : "idS2ESA_PayTrmPTCodeIP",
		S2ESAPAYTRMEXOTHIP : "idS2ESA_PayTrmExOthIP",
		S2ESAPAYTRMPTDESIP : "idS2ESA_PayTrmPTDesIP",
		S2ESASHPTRMVBX : "idEsa_ShpTrmVBox",
		S2ESASPSHPCONVBX : "idEsa_SpShipConVBox",
		S2ESAPREAGREEIP : "idS2ESA_PreAgreeIP",
		S2ESATABMAIP : "idS2ESATAMBAIP",
		S2ESAEQUIPAGREEIP : "idS2ESA_EqipAgreeIP",
		S2ESAEQUIPSOFTOTHSELIP : "idS2ESA_EqipSoftOthSelIP",
		S2ESAEVALTSNDDATIP : "idS2ESA_EvalTsNDDatIP",
		S2ESAPRCTSSALPRCIP : "idS2ESA_PrcTSalPrcIP",
		S2ESAPRCTBSALPRCIP : "idS2ESA_PrcBSalPrcIP",
		S2ESAPRCCOMTBSALPRCIP : "idS2ESA_PrcComBSalPrcIP",
		S2ESAPRCGRSMARTARIP : "idS2ESA_PrcGrsMarTarIP",
		S2ESAPRCGRSMARBOTIP : "idS2ESA_PrcGrsMarBotIP",
		S2ESAPRCJUSTIP : "idS2ESA_PrcJustIP",
		S2ESASHPSTPROTRMIP : "idS2ESA_ShpSTProTermIP",
		S2ESASHPSTDESIP : "idS2ESA_ShpSTDesIP",
		S2ESASHPSTJUSTIP : "idS2ESA_ShpSTJustIP",
		S2ESASHPSTCOMMIP : "idS2ESA_ShpSTComIP",
		S2ESASHPSSRCLOOCIP : "idS2ESA_ShpSSRCLocIP",
		S2ESASHPSSRCJUSTIP : "idS2ESA_ShpSSRCJustIP",
		S2ESASHPSSRCCOMMIP : "idS2ESA_ShpSSRCCommIP",
		S2ESASUPMONTHVALIP : "idS2ESA_SupMonthValIP",
		S2ESASUPEXMONTHVALIP : "idS2ESA_SupExMonthValIP",
		S2ESAPAYTRMJUSTIP : "idS2ESA_PayTrmJustIP",
		S2ESAPAYTRMCOMMIP : "idS2ESA_PayTrmComIP",
		S2ESAPRETRMCOMCKB : "idS2ESA_PreAgreeCkb",
		S2ESAEQUIPMCKB : "idS2ESA_EquipCkb",
		S2ESAABTUPGDCKB : "idS2ESA_AbTUpgrCkb",
		S2ESASUPPORTCKB : "idS2ESA_suprtCkb",
		S2ESAEVALTSNDENDDTPKR : "idS2ESA_EvalTsNDEndDtDP",
		S2ESAEVALTSNDSTARTDTPKR : "idS2ESA_EvalTsNDStartDtDP",
		S2ESAEVALTSNDESTSHIPDTPKR : "idS2ESA_EvalTsNDEstShipDtDP",
		S2ESAIDESUPRTLBL1 : "id_Esa_SuppLbl1",
		S2ESAIDESUPRTLBL2 : "id_Esa_SuppLbl2",
		S2ESAIDEVERCOMBX : "id_Esa_VerComBx",
		S2ESAIDEATTCHMNTTABLE : "idEsaAttachTable",
		S2ESAIDEINITRD : "idEsaRdBtnGrp",
		//***********End Of PCR023905: Migrate ESA/IDS db from Lotus Notes to SAP Fiori Q2C App****************
		//***********Start Of PCR025717: Q2C Q4 2019 Enhancements****************
		S2ESAIDEINITDESBX : "idEsaDecisionBox",
		S2ESAIDEPRCEVAIP : "idS2ESA_PrcEVAIP",
		S2ESAIDEPRCVPSIP : "idS2ESA_PrcVPSIP",
		S2ESAIDEPRCHVMIP : "idS2ESA_PrcExSalPrcHVMIP",
		S2ESAIDEHVMSALPRCRD : "idEasPrHVMRdBtnGrp",
		//***********End Of PCR025717: Q2C Q4 2019 Enhancements******************
		LARGE_ORDER_HBSEARCH : "idS1_OPP_HB_LOW",
		VC_PRDDIS_HBSEARCH : "idS1_OPP_HB_VCPRDDIS",
		FILTER_STAT_HBSEARCH : "idS1_OPP_HB_STAT",
		PSR_STAT_HBSEARCH : "idS1_OPP_HB_PSRSTAT",
		PDC_STAT_HBSEARCH : "idS1_OPP_HB_PDCSTAT",
		CBC_STAT_HBSEARCH : "idS1_OPP_HB_CBCSTAT",
		FILTER_TYP_HBSEARCH : "idS1_OPP_HB_TYP",
		PSR_TYP_HBSEARCH : "idS1_OPP_HB_PSRTYP",
		CBC_TYP_HBSEARCH : "idS1_OPP_HB_CBCVER",
		
		LARGE_ORDER_LBSEARCH : "idS1_OPP_LB_LOW",
		PSR_STAT_LBSEARCH : "idS1_OPP_LB_PSRSTAT",
		PSR_TYP_LBSEARCH : "idS1_OPP_LB_PSRTYP",
		
		/************Opportunity Master Table************/
		OPPORTUNITY_LIST : "idS1_OpportunityTable",
		OPPRTUNITY_TABLE: "idS1_SWOpportunityTable",
		TAB_HDR_GLB_SEARCH: "idS1_GLBSearch",
		TAB_HDR_SHOWALL_BTN : "idS1_BtnShowAll",
		TAB_HDR_PERSONALIZE_BTN : "idS1_BtnPersFltr",
		OPPORTUNITY_LIST_TEMPLATE : "idS1_templateOppList",
		OPPORTUNITY_LIST_FAB_COLUMN : "idS1_FABCOLUMN",
		OPPORTUNITY_LIST_OPPLNE_COLUMN : "idS1_OPPLNECOLUMN",
		OPPORTUNITY_LIST_RGN_COLUMN : "idS1_OPPRGNCOLUMN",
		OPPORTUNITY_LIST_STAT_COLUMN : "idS1_OPPSTATCOLUMN",
		
		OPPORTUNITY_LIST_PSRSTAT_COLUMN : "idS1_OPPPSRSTATCOLUMN",
		OPPORTUNITY_LIST_PDCSTAT_COLUMN : "idS1_OPPPDCSTATCOLUMN",
		OPPORTUNITY_LIST_CBCSTAT_COLUMN : "idS1_OPPCBCSTATCOLUMN",
		OPPORTUNITY_LIST_PSRCURRSTAT_COLUMN : "idS1_OPPPSRCURRSTATCOLUMN",
		OPPORTUNITY_LIST_PDCCURRSTAT_COLUMN : "idS1_OPPPDCCURRSTATCOLUMN",
		OPPORTUNITY_LIST_CBCCURRSTAT_COLUMN : "idS1_OPPCBCCURRSTATCOLUMN",
		OPPORTUNITY_LIST_PSRTYP_COLUMN : "idS1_OPPPSRTYPCOLUMN",
		OPPORTUNITY_LIST_CBCTYP_COLUMN : "idS1_OPPCBCVERCOLUMN",
		OPPORTUNITY_LIST_REVQ_COLUMN : "idS1_OPPREVQCOLUMN",
		
		OPPORTUNITY_LIST_TMP_FAB_COLUMN : "idS1_FABCOLUMN2",
		OPPORTUNITY_LIST_TMP_OPPLNE_COLUMN : "idS1_OPPLNECOLUMN2",
		OPPORTUNITY_LIST_TMP_RGN_COLUMN : "idS1_OPPRGNCOLUMN2",
		OPPORTUNITY_LIST_TMP_STAT_COLUMN : "idS1_OPPSTATCOLUMN2",
		
		OPPORTUNITY_LIST_TMP_PSRSTAT_COLUMN : "idS1_OPPPSRSTATCOLUMN2",
		OPPORTUNITY_LIST_TMP_PDCSTAT_COLUMN : "idS1_OPPPDCSTATCOLUMN2",
		OPPORTUNITY_LIST_TMP_CBCSTAT_COLUMN : "idS1_OPPCBCSTATCOLUMN2",
		OPPORTUNITY_LIST_TMP_PSRCURRSTAT_COLUMN : "idS1_OPPPSRCURRSTATCOLUMN2",
		OPPORTUNITY_LIST_TMP_PDCCURRSTAT_COLUMN : "idS1_OPPPDCCURRSTATCOLUMN2",
		OPPORTUNITY_LIST_TMP_CBCCURRSTAT_COLUMN : "idS1_OPPCBCCURRSTATCOLUMN2",		
		OPPORTUNITY_LIST_TMP_PSRTYP_COLUMN : "idS1_OPPPSRTYPCOLUMN2",
		OPPORTUNITY_LIST_TMP_CBCTYP_COLUMN : "idS1_OPPCBCVERCOLUMN2",
		OPPORTUNITY_LIST_TMP_REVQ_COLUMN : "idS1_OPPREVQCOLUMN2",
 
		
		/**********************S2 View*******************/
		ICON_TAB : "idS2_Icntab",
		ICON_TABF_GINFO : "idS2_IcnF_Ginfo",
		ICON_TABF_ATTACH : "idS2_IcnF_Attach",
		ICON_TABF_PSRSDA : "idS2_IcnF_PSR_SDA",
		ICON_TABF_PDCSDA : "idS2_IcnF_PDC_SDA",
		ICON_TABF_CBC : "idS2_IcnF_CBC",
		ICON_TABF_CARM : "idS2_IcnF_CARM",
		ICON_TABF_MSINFO : "idS2_IcnF_MSInfo",
		ICON_TABF_MLINFO : "idS2_IcnF_MLI",
		ICON_TABF_PSP : "idS2_IcnF_PShip",								  //PCR026551++
		S2FTER_BTN_APPR : "idS2_Ftr_btnApprove",
		S2FTER_BTN_RJCT : "idS2_Ftr_btnReject",
		S2FTER_BTN_RESET : "idS2_Ftr_btnReset",
		/************Justification - PCR018375++ - 3509 - PSR/CBC Workflow Rejection (restart) Capability*****************/
		S2FTER_BTN_CBCRESET : "idS2_Ftr_btnCBCReset",                     //PCR018375++
		S2FTER_BTN_PSPRESET : "idS2_Ftr_btnPspReset",					  //PCR026551++
		S2FTER_BTN_SUBMIT : "idS2_Ftr_btnSubmit",
		S2FTER_BTN_APR_MESSAGE : "idS2_Ftr_btnAprMesgePOver",		
		
		
		
		/********************S2 - GenInfo***************/
		S2GINFO_PANL : "idS2_GenDataPnl",
		/************Phase1.5  2814 code modified*****************/
		S2GINFO_QUOTEREVNUMCOMBOX : "idS2_Gen_QuoteRevNumberCommBox",
		S2GINFO_QUOTEREVNUMBTN : "idS2_Gen_QuoteRevNumberBtn",
		S2GINFO_QUOTEREVNUMTABLE : "idS2_Gen_QuoteRevNumberTbl",
		
		/************End Of Phase1.5  2814 code modified*****************/
		S2GENARAL_INFO_DATA :"GenIData",
		S2GINFO_PANL_SFRM : "idS2_GenDataPnl_SF",
		
		S2GINFO_PANL_CONTACTINFO : "idS2_GenInfo_ContactInfoPnl",
		S2GINFO_PANL_CONTACTINFO_ROMLST : "idS2_Gen_ConInfo_RomList",
		S2GINFO_PANL_CONTACTINFO_ROMAddBtn:"idS2_Gen_ConInfo_RomAddBtn",
		S2GINFO_PANL_CONTACTINFO_ROMLSTEMP : "idS2_Gen_ConInfo_RomListTemplate",
		S2GINFO_PANL_CONTACTINFO_POMLST : "idS2_Gen_ConInfo_PomList",
		S2GINFO_PANL_CONTACTINFO_POMAddBtn:"idS2_Gen_ConInfo_PomAddBtn",
		S2GINFO_PANL_CONTACTINFO_POMLSTEMP : "idS2_Gen_ConInfo_PomListTemplate",
		S2GINFO_PANL_CONTACTINFO_GPMLSTEMP : "idS2_Gen_ConInfo_GPMListTemplate",
		S2GINFO_PANL_CONTACTINFO_TPSLSTEMP : "idS2_Gen_ConInfo_TPSListTemplate",
		S2GINFO_PANL_CONTACTINFO_BUSMELSTEMP : "idS2_Gen_ConInfo_BUSMEListTemplate",
		S2GINFO_PANL_CONTACTINFO_GPMLST : "idS2_Gen_ConInfo_GPMList",
		S2GINFO_PANL_CONTACTINFO_TPSLST : "idS2_Gen_ConInfo_TPSList",
		S2GINFO_PANL_CONTACTINFO_BUSMELST : "idS2_Gen_ConInfo_BUSMEList",
		S2GINFO_PANL_CONTACTINFO_BUSMEAddBtn : "idS2_Gen_ConInfo_BUSMEAddBtn",
		S2GINFO_PANL_CONTACTINFO_TPSKATAddBtn : "idS2_Gen_ConInfo_TPSKATAddBtn",
		S2GINFO_PANL_CONTACTINFO_GPMAddBtn : "idS2_Gen_ConInfo_GPMAddBtn",
		S2GINFO_PANL_CONTACTINFO_BMHEADLST : "idS2_Gen_ConInfo_BMHeadList",
		S2GINFO_PANL_CONTACTINFO_BMHeadAddBtn:"idS2_Gen_ConInfo_BMHeadAddBtn",
		S2GINFO_PANL_CONTACTINFO_BMHEADLSTEMP : "idS2_Gen_ConInfo_BMHeadListTemplate",
        S2GINFO_PANL_CONTACTINFO_SALSLST : "idS2_Gen_ConInfo_SalesList",
        S2GINFO_PANL_CONTACTINFO_SALSAddBtn:"idS2_Gen_ConInfo_SALSAddBtn",
        S2GINFO_PANL_CONTACTINFO_SALSLSTEMP : "idS2_Gen_ConInfo_SalesListTemplate",
        S2GINFO_PANL_CONTACTINFO_BMOLST : "idS2_Gen_ConInfo_BMOList",
        S2GINFO_PANL_CONTACTINFO_BMOAddBtn:"idS2_Gen_ConInfo_BMOAddBtn",
        S2GINFO_PANL_CONTACTINFO_BMOLSTEMP : "idS2_Gen_ConInfo_BMOListTemplate",
        S2GINFO_PANL_CONTACTINFO_PLHEADLST : "idS2_Gen_ConInfo_PLHeadList",
        S2GINFO_PANL_CONTACTINFO_PLHEADAddBtn:"idS2_Gen_ConInfo_PLHeadAddBtn",
        S2GINFO_PANL_CONTACTINFO_PLHEADLSTEMP : "idS2_Gen_ConInfo_PLHeadListTemplate",
        S2GINFO_PANL_CONTACTINFO_ASMEHEADLST : "idS2_Gen_ConInfo_ASMEHeadList",
        S2GINFO_PANL_CONTACTINFO_ASMEHEADAddBtn:"idS2_Gen_ConInfo_ASMEHeadAddBtn",
        S2GINFO_PANL_CONTACTINFO_ASMEHEADLSTEMP : "idS2_Gen_ConInfo_ASMEHeadListTemplate",
        S2GINFO_PANL_CONTACTINFO_PMLST : "idS2_Gen_ConInfo_PMList",
        S2GINFO_PANL_CONTACTINFO_PMAddBtn:"idS2_Gen_ConInfo_PMAddBtn",
        S2GINFO_PANL_CONTACTINFO_PMLSTEMP : "idS2_Gen_ConInfo_PMListTemplate",
        S2GINFO_PANL_CONTACTINFO_CONLST : "idS2_Gen_ConInfo_ConList",
        S2GINFO_PANL_CONTACTINFO_CONddBtn:"idS2_Gen_ConInfo_ConAddBtn",
        S2GINFO_PANL_CONTACTINFO_CONLSTEMP : "idS2_Gen_ConInfo_ConListTemplate",
        /************Phase1.5  2833 code modified*****************/
        S2GINFO_PANL_MAIN_COMMENT_PANEL : "idS2_Gen_MCommentPnl",
        S2GINFO_PANL_MAIN_COMMENT_TEXT_AREA : "idS2_Gen_MainComtTxtArea",
        S2GINFO_PANL_MAIN_COMMENT_SAVEBTN : "idS2_Gen_MainComSaveBtn",
        S2GINFO_PANL_MAIN_COMMENT_COMMTABLE : "idS2_Gen_MainCommTab",
        /************End Of Phase1.5  2833 code modified*****************/
        S2GINFO_PANL_TRANSHIS : "idS2_Gen_TransHisPnl",
        S2GINFO_PANL_TRANSHIS_TRANHIS_TABLE : "idS2_OppTransHisTable",
        S2GINFO_PANL_TRANSHIS_TRANHIS_LISTTAMP : "idS2_OppTransHisTableTemplate",
        
        /************************S2 - ATTACHMENT*******************/
        S2ATTACHMENT_PANL_GENARALBOOKING_PANEL : "idS2GenBookDocPnl",
        S2ATTACHMENT_PANL_GENARALBOOKING_TABLE:"idS2GeneralDocTable",
        S2ATTACHMENT_PANL_GENARALBOOKING_PANEL_CHOOSEBtn : "idS2_Attach_GBDoc_ChooseBtn",
        S2ATTACHMENT_PANL_BOOKING_PANEL : "idS2BookDocPnl",
        S2ATTACHMENT_PANL_BOOKING_TABLE : "idS2BookingDocTable",
        S2ATTACHMENT_PANL_BOOKING_OTHERBtn:"idS2OthersBtn",
        S2ATTACHMENT_PANL_POSTBOOKINGCHANGE_PANEL : "idS2PostBookChgPnl",
        S2ATTACHMENT_PANL_POSTBOOKINGCHANGE_TABLE : "idS2PostBookChgPnlTable",
        S2ATTACHMENT_PANL_POSTBOOKINGCHANGE_OTHERBtn:"idS2PostBookChgOthersBtn",
        S2ATTACHMENT_PANL_POSTBOOKING_PANEL : "idS2PostBookDocPnl",
        S2ATTACHMENT_PANL_POSTBOOKING_TABLE : "idS2PostBookDocPnlTable",
        S2ATTACHMENT_PANL_POSTBOOKING_OTHERBtn:"idS2PostBookOthersBtn",
        S2ATTACHMENT_PANL_GENARALBOOKING_DATEBtn:"idS2_geninfo_date",
        /************Phase1.5  2833 code modified*****************/
        S2ATTACHMENT_PANL_MAIN_COMMENT_PANEL : "idS2_Atch_MCommentPnl",
        S2ATTACHMENT_PANL_MAIN_COMMENT_TEXT_AREA : "idS2_Atch_MainComtTxtArea",
        S2ATTACHMENT_PANL_MAIN_COMMENT_SAVEBTN : "idS2_Atch_MainComSaveBtn",
        S2ATTACHMENT_PANL_MAIN_COMMENT_COMMTABLE : "idS2_Atch_MainCommTab",
        /************End Of Phase1.5  2833 code modified*****************/
        
        /************************S2 - CaRM*******************/
        S2CaRM_PANL_STATUSBAR : "idS2CarmStatusBar",
        S2CaRM_PANL_STATUS_TEXT : "idS2CarmStatusText",
        S2CaRM_PANL_CANCEL_Btn:"idS2CarmCancelBtn",
        S2CaRM_PANL_EDIT_Btn : "idS2CarmEditBtn",
        S2CaRM_PANL_SAVE_Btn : "idS2CarmSaveBtn",
        S2CaRM_PANL_DECISION_HBOX:"idS2CarmDecisionBox",
        S2CaRM_PANL_RADIOBtn : "idS2PCrmRdBtnGrp",
        S2CaRM_PANL_DECISION_VBOX : "idS2CarmDecisionContent",
        S2CaRM_PANL_DATEPICKER:"idS2CarmDate",
        S2CaRM_PANL_ATTACHMENT_TABLE : "idS2CarmAttTable",
        S2CaRM_PANL_ATTACHMENT_TABLE_TEMPLATE : "idS2CarmTemplate",
        S2CaRM_PANL_CARM_OTHERBtn:"idS2CarmOthersBtn",
        S2CaRM_PANL_FORM_MAINCOMMENT:"idS2SimpleFormMCommentCarm",
        S2CaRM_PANL_MAINCOMMENT_TEXTAREA:"idS2CarmMainComm",
        /************Start Of Phase2  3717 CaRM Main Comments edit issue*****************/
        S2CARM_PANL_MAIN_COMMENT_PANEL : "idS2_Carm_MCommentPnl",
        S2CARM_PANL_MAIN_COMMENT_TEXT_AREA : "idS2_Carm_MainComtTxtArea",
        S2CARM_PANL_MAIN_COMMENT_SAVEBTN : "idS2_Carm_MainComSaveBtn",
        S2CARM_PANL_MAIN_COMMENT_COMMTABLE : "idS2_Carm_MainCommTab",
        /************End Of Phase2  3717 CaRM Main Comments edit issue*****************/
        //**** Start of PCR021481++ : 4190: Q2C Q1/Q2 enhancements ***********
        S2CARM_RESET_LIST_PANEL : "id_Carm_Chng_Hist",
        S2CARM_PANL_ChangeHisTab : "idCarmCmtHist",
        //**** End of PCR021481++ : 4190: Q2C Q1/Q2 enhancements ***********
       
        
        
        /********************S2 - PSR-SDA***************/
        S2PSR_SDA_PANL_DECISIONBox : "idPSRDecisionBox",
        S2PSR_SDA_PANL_FORM_DISPLAY_300:"SimpleFormDisplay300",
        S2PSR_SDA_PANL_RADIOBtnGrp : "idPSRSDARdBtnGrp",
        S2PSR_SDA_PANL_STATUS_BAR : "idStatusBar",
        S2PSR_SDA_PANL_BARSTATUS_TEXT:"idStatusText",
        S2PSR_SDA_PANL_LOOKUP_LISTBtn : "idLookupListBtn",
        S2PSR_SDA_PANL_EDITBtn : "idEditBtn",
        S2PSR_SDA_PANL_SAVEBtn:"idSaveBtn",
        
        S2PSR_SDA_PANL_SFABtn : "idSFAppBtn",
        S2PSR_SDA_PANL_GENARALDATA_PANEL : "idPSRGenDataPnl",
        S2PSR_SDA_PANL_FORM_DISPLAY_482:"SimpleFormDisplay482_Trial",
        S2PSR_SDA_PANL_DECISION_CONTENT : "idPSRDecisionContent",
        S2PSR_SDA_PANL_CONTACTINFO_PANEL : "idPSRContactInfoPnl",
        S2PSR_SDA_PANL_FORM_DISPLAY_489:"SimpleFormDisplay489_Trial",
        S2PSR_SDA_PANL_LIST_9 : "list9",
        S2PSR_SDA_PANL_HEADER_9 : "header9",
        S2PSR_SDA_PANL_ROM_ADDBtn:"idROMAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_9 : "listTemplate9",
        S2PSR_SDA_PANL_LIST_10 : "list10",
        S2PSR_SDA_PANL_HEADER_10:"header10",
        S2PSR_SDA_PANL_SALES_ADDBtn : "idSalesAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_10 : "listTemplate10",
        S2PSR_SDA_PANL_LIST_11:"list11",
        S2PSR_SDA_PANL_HEADER_11 : "header11",
        S2PSR_SDA_PANL_AcSME_ADDBtn : "idAcSMEAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_11:"listTemplate11",
        S2PSR_SDA_PANL_LIST_15 : "list15",
        S2PSR_SDA_PANL_HEADER_15 : "header15",
        S2PSR_SDA_PANL_BMO_ADDBtn:"idBMOAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_15 : "listTemplate15",
        S2PSR_SDA_PANL_POMLIST : "IdPSR_CON_POM",
        S2PSR_SDA_PANL_POMHEADER : "IdPSR_CON_POM_Header",
        S2PSR_SDA_PANL_POM_ADDBtn:"IdPSR_CON_POM_Btn",
        S2PSR_SDA_PANL_POMLIST_TEMPLATE : "IdPSR_CON_POM_lstTemp",
        
        S2PSR_SDA_PANL_LIST_16 : "list16",
        S2PSR_SDA_PANL_HEADER_16 : "header16",
        S2PSR_SDA_PANL_GPM_ADDBtn:"idGPMAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_16 : "listTemplate16",
        S2PSR_SDA_PANL_LIST_17 : "list17",
        S2PSR_SDA_PANL_HEADER_17 :"header17",
        S2PSR_SDA_PANL_TPSKAT_ADDBtn : "idTPSKATAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_17 : "listTemplate17",
        S2PSR_SDA_PANL_LIST_18 :"list18",
        S2PSR_SDA_PANL_HEADER_18 : "header18",
        S2PSR_SDA_PANL_BUSME_ADDBtn : "idBUSMEAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_18 :"listTemplate18",
        S2PSR_SDA_PANL_LIST_12 : "list12",
        S2PSR_SDA_PANL_HEADER_12 : "header12",
        S2PSR_SDA_PANL_BMHead_ADDBtn:"idBMHeadAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_12 : "listTemplate12",
        S2PSR_SDA_PANL_LIST_13 : "list13",
        S2PSR_SDA_PANL_HEADER_13:"header13",
        S2PSR_SDA_PANL_CNTROLLER_ADDBtn : "idCntlrAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_13 : "listTemplate13",
        S2PSR_SDA_PANL_LIST_14 : "list14",
        S2PSR_SDA_PANL_HEADER_14:"header14",
        S2PSR_SDA_PANL_PLHead_ADDBtn : "idPLHeadAddBtn",
        S2PSR_SDA_PANL_LIST_TEMPLATE_14 : "listTemplate14",
        S2PSR_SDA_PANL_MANDAT_FID:"idMandatFld",
        S2PSR_SDA_PANL_SAF_RADIOBtn : "idSAFRdBtnGrp",
        S2PSR_SDA_PANL_RB3_3 : "RB3-3",
        S2PSR_SDA_PANL_RB3_1:"RB3-1",
        S2PSR_SDA_PANL_RB3_2 : "RB3-2",
        S2PSR_SDA_PANL_CARBON_COPY_PANEL : "idPSRSDACbnCpyPnl",
        S2PSR_SDA_PANL_LB_CARBON_COPY_TEXT : "idS2_PSRSDA_LB_CbnCpyText",
        S2PSR_SDA_PANL_IP__CARBON_COPY_BOX:"idS2_PSRSDA_IP_CbnCpyBox",
        S2PSR_SDA_PANL_IP_CARBON_COPY : "idS2_PSRSDA_IP_CbnCpy",
        S2PSR_SDA_PANL_LB_CARBON_COPY_BOX : "idS2_PSRSDA_LB_CbnCpyBox",
        S2PSR_SDA_PANL_BT_CARBON_COPY_BOX:"idS2_PSRSDA_BT_CbnCpyBox",
        S2PSR_SDA_PANL_CARBON_COPY_TABLE : "idPSRSDACbnCpyTable",
        S2PSR_SDA_PANL_CARBON_COPY_TEMPLATE : "idPSRSDACbnCpyTemplate",
        S2PSR_SDA_PANL_Sys_SpecTYPE_PANEL:"idDetSysSpecTypePnl",
        S2PSR_SDA_PANL_Sys_SpecDETERMINE_TABLE : "idSysSpecDetermineTable",
        S2PSR_SDA_PANL_SALES_Ans_COLOMN : "idSalesAnsCol",
        S2PSR_SDA_PANL_BMO_Ans_COLOMN:"idBMOAnsCol",
        S2PSR_SDA_PANL_DETERMINE_Sys_SpecTYPE_TEMPLATE : "idDetSysSpecTypeTemplate",
        S2PSR_SDA_PANL_SIMPLEFORM_DISPLAY_370 : "SimpleFormDisplay370",
        S2PSR_SDA_PANL_SIMPLEFORM_DISPLAY_360 : "SimpleFormDisplay360",
        S2PSR_SDA_PANL_B_APPROVALS_PANEL : "idBApprovalsPnl",
        
        S2PSR_SDA_PANL_STATUS_TEXT:"idPSRStatusTxt",
        S2PSR_SDA_PANL_REL_PERSpec_REW_PANEL : "idRelPerSpecRewPnl",
        S2PSR_SDA_PANL_REL_PERSpec_NIL_LABEL : "idS2_RelPerSpecNILLabel",
        S2PSR_SDA_PANL_IP_REL_PERSpec_NIL_BOX:"idS2_PSRSDA_IP_RelPerSpecNILBox",
        S2PSR_SDA_PANL_IP_REL_PERSpec_NIL_LIST : "S2_PSRSDA_IP_RelPerSpecNIList",
        S2PSR_SDA_PANL_REL_PERSpec_REW_LABEL:"idS2_RelPerSpecRewLabel",
        S2PSR_SDA_PANL_IP_REL_PERSpec_REW_BOX : "idS2_PSRSDA_IP_RelPerSpecRewBox",
        S2PSR_SDA_PANL_IP_REL_PERSpec_REW : "S2_PSRSDA_IP_RelPerSpecRew" ,
        S2PSR_SDA_PANL_LB_REL_PERSpec_BOX : "idS2_PSRSDA_LB_RelPerSpecRewBox",
        S2PSR_SDA_PANL_BT_REL_PERSpec_REW_BOX:"idS2_PSRSDA_BT_RelPerSpecRewBox",
        S2PSR_SDA_PANL_BT_NOTINLIST_BOX : "idS2_PSRSDA_BT_NotInListBox",
        S2PSR_SDA_PANL_BT_NOTINLISTtn:"idS2_PSRSDA_BT_NotInListBtn",
        S2PSR_SDA_PANL_REL_PERSpec_REW_TABLE : "idRelPerSpecRewTable",
        S2PSR_SDA_PANL_REL_PERSpec_REW_TEMPLATE : "idRelPerSpecRewTemplate",
        S2PSR_SDA_PANL_RPSR_DOC_TABLE:"idS2_RPSRDocTable",
        S2PSR_SDA_PANL_RPSR_DOC_TEMPLATE : "idS2_RPSRDocTemplate",
        
        S2PSR_SDA_PANL_EVDANCE_DOC_TABLE:"idEPSRDocTable",
        S2PSR_SDA_PANL_EVDANCE_DOC_TEMPLATE : "idEPSRDocTemplate",
        S2PSR_SDA_PANL_EVDANCE_SSDA_DOC_TABLE:"idESSDAPSRDocTable",
        S2PSR_SDA_PANL_EVDANCE_SSDA_DOC_TEMPLATE : "idESSDAPSRDocTemplate",
        
        S2PSR_SDA_PANL_CUST_SpecREV1_PANEL:"idCustSpecRev1Pnl",
        S2PSR_SDA_PANL_CUST_SpecREV1_TABLE : "idCustSpecRev1Table",
        S2PSR_SDA_PANL_CUST_SpecREV1_TEMPLATE : "idCustSpecRev1Template",
        S2PSR_SDA_PANL_SDAReq_PANEL:"idSDAReqPnl",
        S2PSR_SDA_PANL_SDAReq_TABLE : "idSDAReqTable",
        S2PSR_SDA_PANL_SDAReq_TEMPLATE:"idSDAReqTemplate",
        S2PSR_SDA_PANL_FPSR_DOC_PANEL : "idFPSRDocPnl",
        S2PSR_SDA_PANL_FPSR_DOC_TABLE : "idFPSRDocTable",
        S2PSR_SDA_PANL_FPSR_DOC_TEMPLATE:"idFPSRDocTemplate",
        S2PSR_SDA_PANL_BSDAAsses_PANEL : "idBSDAAssesPnl",
        S2PSR_SDA_PANL_SSDAsses_TEXT_AREA :"idSSDAssesTxtArea",
        
        S2PSR_SDA_PANL_BSDAAsses_FORM:"IdBSDAEVSForm",
        S2PSR_SDA_PANL_SDAsses_COMBO_BOX : "idSDAssesComBx",
        S2PSR_SDA_PANL_DEP_CHECKBOX : "idDepChkBx",
        S2PSR_SDA_PANL_BSDA_EVIDENCE_LINK_BOX:"idBSDAEvidenceLinkHBox",
        S2PSR_SDA_PANL_BSDA_EVIDENCE_LINK : "idBSDAEvidenceLink",
        S2PSR_SDA_PANL_BSDA_EVIDENCE_UPLOAD_VBOX:"idBSDAEvidenceUploadVBox",
        S2PSR_SDA_PANL_EVIDENCE_Btn : "idEvidenceBtn",
        S2PSR_SDA_PANL_SDASSES_TEXT_AREA : "idSDAssesTxtArea",
        S2PSR_SDA_PANL_SIMPLE_FORM_DISPLAY_435:"SimpleFormDisplay435",
        S2PSR_SDA_PANL_SMANDAT_FID : "idSMandatFld",
        S2PSR_SDA_PANL_EXPSSDA_RADIOBtn_GROUP:"idEXPSSDARdBtnGrp",
        S2PSR_SDA_PANL_RB4_3 : "RB4-3",
        S2PSR_SDA_PANL_RB4_1 : "RB4-1",
        S2PSR_SDA_PANL_RB4_2:"RB4-2",
        S2PSR_SDA_PANL_BSSDAAsses_PANEL : "idBSSDAAssesPnl",
        S2PSR_SDA_PANL_SSDA_EVS_FORM:"IdSSDAEVSForm",
        S2PSR_SDA_PANL_SSDAsses_COMBOBOX : "idSSDAssesComBx",
        S2PSR_SDA_PANL_SDEP_CHECKBOX : "idSDepChkBx",
        S2PSR_SDA_PANL_SEVIDENCE_LINKBOX:"idSEvidenceLinkHBox",
        S2PSR_SDA_PANL_SEVIDENCE_LINK : "idSEvidenceLink",
        
        S2PSR_SDA_PANL_SEVIDENCE_UPLOAD_VBOX:"idSEvidenceUploadVBox",
        S2PSR_SDA_PANL_SEVIDENCE_Btn : "idSEvidenceBtn",
        S2PSR_SDA_PANL_SAPPROVALS_PANEL : "idSApprovalsPnl",
        S2PSR_SDA_PANL_SAPRpARALLEL : "idSAprParallel",
        S2PSR_SDA_PANL_SAPRpARALLEL_TEMPLATE : "idSParlAprTemplate",
        S2PSR_SDA_PANL_SBAPR_FINAL : "idSBAprFinal",
        S2PSR_SDA_PANL_BAPR_FINAL : "idBAprFinancial",
        S2PSR_SDA_PANL_SBAPR_FINAL_TEMPLATE : "idSBAprFinalTemplate",
        S2PSR_SDA_PANL_SAPR_FINANCIAL : "idSAprFinancial",
        S2PSR_SDA_PANL_SAPR_FINANCIAL_TEMPLATE :"idSAprFinancialTemplate",
        S2PSR_SDA_PANL_MAIN_COMMENT_PANEL : "idMCommentPnl",
        S2PSR_SDA_PANL_MAIN_COMMENT__TEXT_AREA : "idMainComtTxtArea",
        S2PSR_SDA_PANL_MAIN_COMMENT__SAVEBTN : "idS2PSRMainComSaveBtn",
        S2PSR_SDA_PANL_MAIN_COMMENT__COMMTABLE : "idPSRMainCommTab",
        
        S2PSR_SDA_PANL_BApr_PARALLEL:"idBAprParallel",
        S2PSR_SDA_PANL_BApr_FINAL:"idBAprFinal",
        S2PSR_SDA_PANL_BT_UnLINKBtn:"idS2_PSRSDA_BT_UnLinkBtn",
        
        /******Start Of PCR017480++ 5454- PSR-SDA / PDC-SDA Recreate process*****/
        S2PSR_SDA_PANL_RESET_LIST_PANEL : "idPSResetListPnl",
        S2PSR_SDA_PANL_RESET_LIST_TABLE : "idPSResetListTab",
        /******End Of PCR017480++ 5454- PSR-SDA / PDC-SDA Recreate process ******/
        
        /************************S2 - CBC*******************/
        S2CBC_PANL_DECISION_BOX : "idCBCDecisionBox",
        S2CBC_PANL_RADIOBtn:"idCBCRdBtnGrp",
        S2CBC_PANL_STATUS_BAR : "idCBCStatusBar",
        S2CBC_PANL_STATUS_TEXT : "idCBCStatusText",
        S2CBC_PANL_EDITBtn:"idCBCEditBtn",
        S2CBC_PANL_SAVEBtn : "idCBCSaveBtn",
        S2CBC_PANL_SFAppBtn: "idCBCSFAppBtn",
        S2CBC_PANL_GENERAL_DATA_PANEL:"idCBCGenDataPnl",
        S2CBC_PANL_SIMPLE_FORM_582 : "SimpleFormDisplay582_Trial",
        S2CBC_PANL_DECISION_CONTENT : "idCBCDecisionContent",
        S2CBC_PANL_CONTACTINFO_PANEL:"idCBCContactInfoPnl",
        S2CBC_PANL_CONTACTINFO_ROM_LIST : "idS2_CBC_ConInfo_RomList",
        S2CBC_PANL_HEADER_19 : "header19",
        S2CBC_PANL_HEADER_20:"header20",
        S2CBC_PANL_HEADER_21 : "header21",
        
        S2CBC_PANL_CONTACTINFO_BOMLST : "idS2_CBC_ConInfo_BMOList",
        S2CBC_PANL_CONTACTINFO_ROMAddBtn:"idS2_CBC_ConInfo_RomAddBtn",
        S2CBC_PANL_CONTACTINFO_ROM_LIST_TEMPLATE : "idS2_CBC_ConInfo_RomListTemplate",
        S2CBC_PANL_CONTACTINFO_POM_LIST : "idS2_CBC_ConInfo_PomList",
        S2CBC_PANL_CONTACTINFO_POMAddBtn:"idS2_CBC_ConInfo_PomAddBtn",
        S2CBC_PANL_CONTACTINFO_POM_LIST_TEMPLATE : "idS2_CBC_ConInfo_PomListTemplate",
        S2CBC_PANL_CONTACTINFO_AUTH_SALEApr_LIST : "idS2_CBC_ConInfo_AuthSaleAprList",
        S2CBC_PANL_CONTACTINFO_AUTH_SALEApr_AddBtn:"idS2_CBC_ConInfo_AuthSaleAprAddBtn",
        S2CBC_PANL_CONTACTINFO_AUTH_SALEApr_LIST_TEMPLATE : "idS2_CBC_ConInfo_AuthSaleAprListTemplate",
        S2CBC_PANL_CONTACTINFO_BOM_LIST : "idS2_CBC_ConInfo_BMOList",
        S2CBC_PANL_CONTACTINFO_BOM_AddBtn:"idS2_CBC_ConInfo_BMOAddBtn",
        S2CBC_PANL_CONTACTINFO_BOM_LIST_TEMPLATE : "idS2_CBC_ConInfo_BMOListTemplate",
        S2CBC_PANL_CONTACTINFO_CONT_LIST : "idS2_CBC_ConInfo_CntrList",
        S2CBC_PANL_CONTACTINFO_CONT_AddBtn:"idS2_CBC_ConInfo_CntrAddBtn",
        S2CBC_PANL_CONTACTINFO_CONT_LIST_TEMPLATE : "idS2_CBC_ConInfo_CntrListTemplate",
        
        S2CBC_PANL_CC_PANEL : "idCBCCbnCpyPnl",
        S2CBC_PANL_LB_CC_TEXT:"idS2_CBC_LB_CbnCpyText",
        S2CBC_PANL_IP_CC_BOX : "idS2_CBC_IP_CbnCpyBox",
        S2CBC_PANL_IP_CC : "idS2_CBC_IP_CbnCpy",
        S2CBC_PANL_LB_CC_BOX:"idS2_CBC_LB_CbnCpyBox",
        S2CBC_PANL_BT_CC_BOX : "idS2_CBC_BT_CbnCpyBox",
        S2CBC_PANL_CC_TABLE : "idCBCCbnCpyTable",
        S2CBC_PANL_CC_TEMPLATE:"idCBCCbnCpyTemplate",
        S2CBC_PANL_Q_PANEL : "idCBCQuesPnl",
        S2CBC_PANL_Q_CONTENT : "idS2_CBC_QuesCont",
        S2CBC_PANL_Q_TABLE: "IdS2_CBC_QuesTable",
        S2CBC_PANL_Q_TABLEHDR: "IdS2_CBC_QuesTableHeader",
        S2CBC_PANL_Q_RADIOBtn : "idCBCSaleQusRdBtnGrp",
        S2CBC_PANL_BMO_Q_RADIOBtn : "idCBCBMOQusRdBtnGrp",
        S2CBC_PANL_APR_PANEL:"idCBCAprPnl",
        S2CBC_PANL_APPROVERS : "idCBCApprovers",
        
        S2CBC_PANL_APPROVERS_TEMPLATE : "idCBCApproversTemplate",
        /******Start Of PCR018375++ PSR/CBC Workflow Rejection(restart) Capability*****/
        S2CBC_PANL_MEA_DOC_PANEL : "idCBCMEADocPnl",
        S2CBC_PANL_MEA_DOC_CHOOSE_BTN : "idCBC_MEADoc_ChooseBtn",
        S2CBC_PANL_MEA_DOC_LIST_TABLE : "idCBC_MEADoc_Table",
        S2CBC_PANL_RESET_LIST_PANEL : "idCBCResetListPnl",
        S2CBC_PANL_RESET_LIST_TABLE : "idCBCResetListTab",
        /******End Of PCR018375++ PSR/CBC Workflow Rejection(restart) Capability*****/
        /******Start Of PCR022669: Q2C Q2 UI Changes*****/
        S2CBC_PANL_CNGHISPNL : "id_Cbc_Chng_Hist",
        S2CBC_PANL_CNGHISTAB : "idCBCCmtHist",
        /******Start Of PCR022669: Q2C Q2 UI Changes*****/
        S2CBC_PANL_MAIN_COMMENT_PANEL:"idCBCMCommentPnl",
        S2CBC_PANL_MAIN_COMMENT_TEXT_AREA : "idCBCMainComtTxtArea",
        S2CBC_PANL_MESSAGE_POPOVER : "idMessagePopover",
        S2CBC_PANL_MAIN_COMMENT__SAVEBTN : "idS2CBCMainComSaveBtn",
        S2CBC_PANL_MAIN_COMMENT__COMMTABLE : "idCBCMainCommTab",
        
        
        /********************S2 - PDC-SDA***************/
        S2PDC_SDA_PANL_DECISIONBox : "idPDCDecisionBox",
        S2PDC_SDA_PANL_FORM_DISPLAY_300:"SimpleFormDisplay300_PDC",
        S2PDC_SDA_PANL_RADIOBtnGrp : "idPDCSDARdBtnGrp",
        S2PDC_SDA_PANL_STATUS_BAR : "idPdcStatusBar",
        S2PDC_SDA_PANL_BARSTATUS_TEXT:"idPdcStatusText",
        S2PDC_SDA_PANL_LOOKUP_LISTBtn : "idPdcLookupListBtn",
        S2PDC_SDA_PANL_EDITBtn : "idPdcEditBtn",
        S2PDC_SDA_PANL_SAVEBtn:"idPdcSaveBtn",
        
        S2PDC_SDA_PANL_SFABtn : "idPdcSFAppBtn",
        S2PDC_SDA_PANL_GENARALDATA_PANEL : "idPDCGenDataPnl",
        S2PDC_SDA_PANL_FORM_DISPLAY_482:"SimpleFormDisplay482_Trial_Pdc",
        S2PDC_SDA_PANL_DECISION_CONTENT : "idPDCDecisionContent",
        S2PDC_SDA_PANL_CONTACTINFO_PANEL : "idPDCContactInfoPnl",
        S2PDC_SDA_PANL_FORM_DISPLAY_489:"SimpleFormDisplay489_Trial_Pdc",
        S2PDC_SDA_PANL_ROM : "id_Pdc_Rom",
        S2PDC_SDA_PANL_HEADER_9 : "id_Pdc_Rom_header",
        S2PDC_SDA_PANL_ROM_ADDBtn:"id_Pdc_ROMAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_9 : "id_Pdc_RomlistTemplate",
        S2PDC_SDA_PANL_SALES_LIST : "id_Pdc_Sales",
        S2PDC_SDA_PANL_SALES_HEADER:"id_Pdc_Sales_header",
        S2PDC_SDA_PANL_SALES_ADDBtn : "id_Pdc_SalesAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_10 : "id_Pdc_SaleslistTemplate",
        S2PDC_SDA_PANL_ASME_LIST:"id_Pdc_ASME",
        S2PDC_SDA_PANL_ASME_HEADER : "id_Pdc_ASME_header",
        S2PDC_SDA_PANL_AcSME_ADDBtn : "id_Pdc_ASMEAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_11:"id_Pdc_ASMElistTemplate",
        S2PDC_SDA_PANL_POM_LIST : "id_Pdc_POM",
        S2PDC_SDA_PANL_POM_HEADER : "id_Pdc_POM_header",
        S2PDC_SDA_PANL_BMO_ADDBtn:"id_Pdc_POMAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_15 : "id_Pdc_POMlistTemplate",
        S2PDC_SDA_PANL_BMO_LIST : "id_Pdc_BMO",
        S2PDC_SDA_PANL_BMO_HEADER : "id_Pdc_BMO_header",
        S2PDC_SDA_PANL_GPM_ADDBtn:"id_Pdc_BMOAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_16 : "id_Pdc_BMOlistTemplate",
        S2PDC_SDA_PANL_BUSME_LIST : "id_Pdc_BUSME",
        S2PDC_SDA_PANL_BUSME_HEADER :"id_Pdc_BUSME_header",
        S2PDC_SDA_PANL_BUSME_ADDBtn : "id_Pdc_BUSMEAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_17 : "id_Pdc_BUSMElistTemplate",
        S2PDC_SDA_PANL_GSM_LIST :"id_Pdc_GSM",
        S2PDC_SDA_PANL_GSM_HEADER : "id_Pdc_GSM_header",
        S2PDC_SDA_PANL_GSM_ADDBtn : "id_Pdc_GSMAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_18 :"id_Pdc_GSMlistTemplate",
        S2PDC_SDA_PANL_RBM_LIST : "id_Pdc_RBM",
        S2PDC_SDA_PANL_RBM_HEADER_ : "id_Pdc_RBM_header",
        S2PDC_SDA_PANL_RBM_ADDBtn:"id_Pdc_RBMAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_12 : "id_Pdc_RBMlistTemplate",
        S2PDC_SDA_PANL_PLHEAD_LIST : "id_Pdc_PLHead",
        S2PDC_SDA_PANL_PLHEAD_HEADER:"id_Pdc_PLHead_header",
        S2PDC_SDA_PANL_PLHEAD_ADDBtn : "id_Pdc_PLHeadAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_13 : "id_Pdc_PLHeadlistTemplate",
        S2PDC_SDA_PANL_CON_LIST : "id_Pdc_CON",
        S2PDC_SDA_PANL_CON_HEADER:"id_Pdc_CON_header",
        S2PDC_SDA_PANL_CON_ADDBtn : "id_Pdc_CONAddBtn",
        S2PDC_SDA_PANL_LIST_TEMPLATE_14 : "id_Pdc_CONlistTemplate",
        S2PDC_SDA_PANL_FORM_360 : "SimpleFormDisplay360_Pdc",
        S2PDC_SDA_PANL_MANDAT_FID : "id_Pdc_MandatFld",
        S2PDC_SDA_PANL_SAF_RADIOBtn : "id_Pdc_SAFRdBtnGrp",
        S2PDC_SDA_PANL_RB3_3 : "id_Pdc_RB3-3",
        S2PDC_SDA_PANL_RB3_1:"id_Pdc_RB3-1",
        S2PDC_SDA_PANL_RB3_2 : "id_Pdc_RB3-2",
        S2PDC_SDA_PANL_CARBON_COPY_PANEL : "idPDCSDACbnCpyPnl",
        S2PDC_SDA_PANL_LB_CARBON_COPY_TEXT : "idS2_PDCSDA_LB_CbnCpyText",
        S2PDC_SDA_PANL_IP__CARBON_COPY_BOX:"idS2_PDCSDA_IP_CbnCpyBox",
        S2PDC_SDA_PANL_IP_CARBON_COPY : "idS2_PDCSDA_IP_CbnCpy",
        S2PDC_SDA_PANL_LB_CARBON_COPY_BOX : "idS2_PDCSDA_LB_CbnCpyBox",
        S2PDC_SDA_PANL_BT_CARBON_COPY_BOX:"idS2_PDCSDA_BT_CbnCpyBox",
        S2PDC_SDA_PANL_BT_CARBON_COPY: "idS2_PDCSDA_BT_CbnCpy",
        S2PDC_SDA_PANL_CARBON_COPY_TABLE : "idPDCSDACbnCpyTable",
        S2PDC_SDA_PANL_CARBON_COPY_TEMPLATE : "idPDCSDACbnCpyTemplate",
        
        S2PDC_SDA_PANL_SIMPLEFORM_DISPLAY_370 : "SimpleFormDisplay370_Pdc",
        
        
        S2PDC_SDA_PANL_STATUS_TEXT:"idPDCStatusTxt",
        S2PDC_SDA_PANL_REL_PERSpec_REW_PANEL : "id_Pdc_RelPerSpecRewPnl",
        S2PDC_SDA_PANL_REL_PERSpec_NIL_LABEL : "idS2_Pdc_RelPerSpecNILLabel",
        S2PDC_SDA_PANL_IP_REL_PERSpec_NIL_BOX:"idS2_PDCSDA_IP_RelPerSpecNILBox",
        S2PDC_SDA_PANL_IP_REL_PERSpec_NIL_LIST : "S2_PDCSDA_IP_RelPerSpecNIList",
        S2PDC_SDA_PANL_REL_PERSpec_REW_LABEL:"idS2_Pdc_RelPerSpecRewLabel",
        S2PDC_SDA_PANL_IP_REL_PERSpec_REW_BOX : "idS2_PDCSDA_IP_RelPerSpecRewBox",
        S2PDC_SDA_PANL_IP_REL_PERSpec_REW : "S2_PDCSDA_IP_RelPerSpecRew" ,
        S2PDC_SDA_PANL_LB_REL_PERSpec_BOX : "idS2_PDCSDA_LB_RelPerSpecRewBox",
        S2PDC_SDA_PANL_BT_REL_PERSpec_REW_BOX:"idS2_PDCSDA_BT_RelPerSpecRewBox",
        S2PDC_SDA_PANL_BT_NOTINLIST_BOX : "idS2_PDCSDA_BT_NotInListBox",
        S2PDC_SDA_PANL_BT_NOTINLISTtn: "idS2_PDCSDA_BT_NotInListBtn",
        S2PDC_SDA_PANL_REL_PERSpec_REW_TABLE : "id_Pdc_RelPerSpecRewTable",
        S2PDC_SDA_PANL_REL_PERSpec_REW_TEMPLATE : "id_Pdc_RelPerSpecRewTemplate",
        S2PDC_SDA_PANL_RPDC_DOC_TABLE: "idS2_RPDCDocTable",
        S2PDC_SDA_PANL_RPDC_DOC_TEMPLATE : "idS2_RPDCDocTemplate",
        
        S2PDC_SDA_PANL_EVPDC_DOC_TABLE: "idEPDCDocTable",
        S2PDC_SDA_PANL_EVPDC_DOC_TEMPLATE : "idEPDCDocTemplate",
        S2PDC_SDA_PANL_SEVPDC_DOC_TABLE: "idESSDAPDCDocTable",
        S2PDC_SDA_PANL_SEVPDC_DOC_TEMPLATE : "idESSDAPDCDocTemplate",
        
        S2PDC_SDA_PANL_CUST_SpecREV1_PANEL:"id_Pdc_CustSpecRev1Pnl",
        S2PDC_SDA_PANL_CUST_SpecREV1_TABLE : "id_Pdc_CustSpecRev1Table",
        S2PDC_SDA_PANL_CUST_SpecREV1_TEMPLATE : "id_Pdc_CustSpecRev1Template",
     
        S2PDC_SDA_PANL_FPDC_DOC_PANEL : "idFPDCDocPnl",
        S2PDC_SDA_PANL_FPDC_DOC_TABLE : "idFPDCDocTable",
        S2PDC_SDA_PANL_FPDC_DOC_TEMPLATE:"idFPDCDocTemplate",
        S2PDC_SDA_PANL_BSDAAsses_PANEL : "id_Pdc_BSDAAssesPnl",
        
        
        S2PDC_SDA_PANL_BSDAAsses_FORM:"Id_Pdc_BSDAEVSForm",
        S2PDC_SDA_PANL_SDAsses_COMBO_BOX : "id_Pdc_SDAssesComBx",
        S2PDC_SDA_PANL_DEP_CHECKBOX : "id_Pdc_DepChkBx",
        S2PDC_SDA_PANL_BSDA_EVIDENCE_LINK_BOX:"id_Pdc_BSDAEvidenceLinkHBox",
        S2PDC_SDA_PANL_BSDA_EVIDENCE_LINK : "id_Pdc_BSDAEvidenceLink",
        S2PDC_SDA_PANL_BSDA_EVIDENCE_UPLOAD_VBOX:"id_Pdc_BSDAEvidenceUploadVBox",
        S2PDC_SDA_PANL_EVIDENCE_Btn : "id_Pdc_EvidenceBtn",
        S2PDC_SDA_PANL_SDASSES_TEXT_AREA : "id_Pdc_SDAssesTxtArea",
        S2PDC_SDA_PANL_SIMPLE_FORM_DISPLAY_435:"SimpleFormDisplay435_Pdc",
        S2PDC_SDA_PANL_SMANDAT_FID : "id_Pdc_SMandatFld",
        S2PDC_SDA_PANL_EXPSSDA_RADIOBtn_GROUP:"id_Pdc_EXPSSDARdBtnGrp",
        S2PDC_SDA_PANL_RB4_3 : "id_Pdc_RB4-3",
        S2PDC_SDA_PANL_RB4_1 : "id_Pdc_RB4-1",
        S2PDC_SDA_PANL_RB4_2:"id_Pdc_RB4-2",
        S2PDC_SDA_PANL_BSSDAAsses_PANEL : "id_Pdc_BSSDAAssesPnl",
        S2PDC_SDA_PANL_SSDA_EVS_FORM:"IdS_Pdc_SDAEVSForm",
        S2PDC_SDA_PANL_SSDAsses_COMBOBOX : "id_Pdc_SSDAssesComBx",
        S2PDC_SDA_PANL_SDEP_CHECKBOX : "id_Pdc_SDepChkBx",
        S2PDC_SDA_PANL_SEVIDENCE_LINKBOX:"id_Pdc_SEvidenceLinkHBox",
        S2PDC_SDA_PANL_SEVIDENCE_LINK : "id_Pdc_SEvidenceLink",
        
        S2PDC_SDA_PANL_SEVIDENCE_UPLOAD_VBOX:"id_Pdc_SEvidenceUploadVBox",
        S2PDC_SDA_PANL_SSDASSESTXTAREA:"id_Pdc_SSDAssesTxtArea",
        S2PDC_SDA_PANL_SEVIDENCE_Btn : "id_Pdc_SEvidenceBtn",
        S2PDC_SDA_PANL_SAPPROVALS_PANEL : "id_Pdc_SApprovalsPnl",
        S2PDC_SDA_PANL_SAPRpARALLEL : "id_Pdc_SAprParallel",
        S2PDC_SDA_PANL_SAPRpARALLEL_TEMPLATE : "id_Pdc_SParlAprTemplate",
        S2PDC_SDA_PANL_SBAPR_FINAL : "id_Pdc_SBAprFinal",
        S2PDC_SDA_PANL_BAPR_FINAL : "id_Pdc_BAprFinancial",
        S2PDC_SDA_PANL_SBAPR_FINAL_TEMPLATE : "id_Pdc_SBAprFinalTemplate",
        S2PDC_SDA_PANL_SAPR_FINANCIAL : "id_Pdc_SAprFinancial",
        S2PDC_SDA_PANL_SAPR_FINANCIAL_TEMPLATE :"id_Pdc_SAprFinancialTemplate",
        S2PDC_SDA_PANL_BAPPROVAL_PANEL:"id_Pdc_BApprovalsPnl",
        S2PDC_SDA_PANL_MAIN_COMMENT_PANEL : "id_Pdc_MCommentPnl",
        S2PDC_SDA_PANL_MAIN_COMMENT__TEXT_AREA : "id_Pdc_MainComtTxtArea",
        S2PDC_SDA_PANL_MAIN_COMMENT_SAVEBtn:"idS2PDCMainComSaveBtn",
        S2PDC_SDA_PANL_MAIN_COMMENT_TABLE:"idPDCMainCommTab",
        S2PDC_SDA_PANL_MAIN_COMMENT__SAVEBTN : "idS2PDCMainComSaveBtn",
        S2PDC_SDA_PANL_MAIN_COMMENT__COMMTABLE : "idPDCMainCommTab",
        
        /******Start Of PCR017480++ 5454- PSR-SDA / PDC-SDA Recreate process*****/
        S2PDC_SDA_PANL_RESET_LIST_PANEL : "idPDCResetListPnl",
        S2PDC_SDA_PANL_RESET_LIST_TABLE : "idPDCResetListTab",
        /******End Of PCR017480++ 5454- PSR-SDA / PDC-SDA Recreate process ******/
        S2PDC_SDA_PANL_BApr_PARALLEL:"id_Pdc_BAprParallel",
        S2PDC_SDA_PANL_BApr_PARALLEL_TEMPLATE:"id_Pdc_ParlAprTemplate",
        S2PDC_SDA_PANL_BApr_FINAL:"id_Pdc_BAprFinal",
        S2PDC_SDA_PANL_BApr_FINAL_TEMPLATE:"id_Pdc_BAprFinalTemplate",
        S2PDC_SDA_PANL_BApr_FINANCIAL:"id_Pdc_BAprFinancial",
        S2PDC_SDA_PANL_BApr_FINANCIAL_TEMPLATE:"id_Pdc_BAprFinancialTemplate",
        S2PDC_SDA_PANL_BT_UnLINKBtn:"idS2_PDCSDA_BT_UnLinkBtn",
        
        
        
        /**********************S3 View*******************/
		S3_TABLE_OTHERDOC: "idOthersDocTable",
		
		/*******************Fragments****************/
		S2_F_ADDCONTACT_CONTACT_TABLE :"idContactTable",
		S2_F_ADDCONTACT_CONTACT_TABLE_TEMPLATE :"templateContactList",
		
		/*******************lookup fragment**********************/
		FRAGICONTAB:"Icntab",
		FRAGTPSICONTAB:"idS2_TPS",
		FRAGTPSTABLE:"idS2_TPS_Table",
		FRAGSMICONTAB:"idS2_GSM",
		FRAGGSMTABLE:"idS2_GSM_Table",
		FRAGRBMICONTAB:"idS2_RBM",
		FRAGRBMTABLE:"idS2_RBM_Table",
		FRAGBMICONTAB:"idS2_IcnF_BM",
		FRAGBMTABLE:"idS2_BMhead_Table",
		FRAGPLICONTAB:"idS2_IcnF_KPU",
		FRAGPLTABLE:"idS2_PLhead_Table",
		FRAGCONICONTAB:"idS2_IcnF_Controller",
		FRAGCONTABLE:"idS2_CON_Table",
		FRAGCOMICONTAB:"idS2_IcnF_Completion",
		FRAGCOMTABLE:"idS2_COM_Table",
		FRAGGENDOCDATE:"id_GDfrag_date",
			
	    /******Start Of PCR026551++ Pre-Shipment development*****/
	    S2PSP_PANL_MAIN_COMMENT_PANEL:"idPSPMCommentPnl",
	    S2PSP_PANL_CNGHISPNL: "id_Psp_Chng_Hist",
	    S2PSP_PANL_CRBNCPYPNL: "idPspCbnCpyPnl",
	    S2PSP_TAB_MAINCOMMENT: "idPspMainCommTab",
	    S2PSP_TAB_GEN_PANEL: "idPSPGenDataPnl",
	    S2PSP_CHG_HISTORY: "idPspCmtHist",
	    S2PSP_STATUS_BAR: "idPspStatusBar",
	    S2PSP_CRBNCPY_TBL: "idPspCbnCpyTable",
	    S2PSP_CRBNCPY_INPUT: "idS2_Psp_IP_CbnCpy",
	    S2PSP_DECISION_BOX: "idPspDecisionBox",
	    S2PSP_RDBTN_GROUP: "idPspRdBtnGrp",
	    S2PSP_QN_PANEL: "idPspQuesPnl",
	    S2PSP_GEN_PANL_FORM_DISPLAY:"SimpleFormDisplay583_Trial",
	    S2PSP_MAIN_COMM_TEXT:"idPspMainComtTxtArea",
	    
	    
	    S2PSP_BTN_SAVE: "idPspSaveBtn",
	    S2PSP_BTN_EDIT: "idPspEditBtn",
	    S2PSP_BTN_SUBMIT: "idPspSFAppBtn",
	    S2PSP_BTN_CANCEL: "idPspCancelBtn",
	    S2PSP_BTN_MAINCOMM_SAVE: "idS2PspMainComSaveBtn",
		
		
	    S2PSP_STATUS_TEXT: "idPspStatusText",
	    S2PSP_QN_TABLE: "IdS2_PSP_QuesTable",
	    S2PSP_MAIN_COMMENT_TEXT: "idPspMainComtTxtArea",
	    S2PSP_PANL_LB_CC_TEXT: "idS2_PSP_LB_CbnCpyText",
	    /******End Of PCR026551++ Pre-Shipment development ******/
		/******Start Of PCR028711 Q2C Enhancements for Q2-20*****/
	    S2ESAPTCTAMSTRAGMT: "idEsaPTStndTermCTA",
		S2ESAPTCTAMSTRAGMT_TEXT : "idS2ESA_PTStndTermIP",
		S1CUSTF4 : "idSAF_AF_CUST",
		S1BQTRF4 : "idSAF_AF_BQTR",
		S1BUF4 : "idSAF_AF_BU",
		S1LODRF4 : "idSAF_AF_LRGODR",
		S2PESA_CRBNCPY_TBL : "idEsaCbnCpyTable",
		S2PESA_CRBNCPY_LBL : "idS2_Esa_LB_CbnCpyText",
		S2PESA_CRBNCPY_INP : "idS2_Esa_IP_CbnCpy",
		S2PESA_PRINT_BTN : "idEsaPrintFuncBtn",
		S2PESA_CC_PNL : "idEsaCbnCpyPnl",
		S2PESA_EXT_BTN : "idEsaReqExtBtn",
		S2PESA_CHKLST_BTN : "idEsaCheckListBtn",
		S2ESA_IDS_PANL_BT_CARBON_COPY_BOX : "idS2_Esa_BT_CbnCpyBox",
		S1HDRREFRESHBTN : "idS1_HDRRefreshBTN",
		S1HDRGOBTN : "idS1_HDRGoBTN",
		S1OPPDOWNLOADBTN : "idS1_OppDownload",
		/******End Of PCR028711 Q2C Enhancements for Q2-20*******/
		//***********Start Of PCR026243 DL:1803 Display Migration to Q2C****************
		S4DISICNTAB:"idS4_Icntab",
		S4DISGENINFO:"idS4_IcnF_Ginfo",
		S4DISCBC:"idS4_IcnF_CBC",
		S4DISCARM:"idS4_IcnF_CARM",
		S4DISATTACH:"idS4_IcnF_Attach",
		S4DISRRA:"idS4_IcnF_PSR_RRA",
		S4DISMLI:"idS4_IcnF_MLI",
		S4DISESA:"idS4_IcnF_ESA",
		S4DISCBCDISBOX:"id_DispCBCDecisionBox",
		S4DISRRADISBOX:"idDispPSRDecisionBox",
		S4DISESADISBOX:"idDispEsaDecisionBox",
		S4DISAPRMSGPOPOVERFTR:"idS4_Ftr_btnAprMesgePOver",
		S4DISRRAREVDOCTAB:"idS4_Disp_RPSRDocTable",
		S4DISRRAREVDOCLINKTAB:"idDispRelPerSpecRewTable",
		S4DISRRACUSTSPECDETERTAB:"idDispCustSpecRev1Table",
		S4DISRRAFNLSPECTAB:"idDispFPSRDocTable",
		S4DISBRRAEVDCETAB:"idDisp_EPSRDocTable",
		S4DISSRRAEVDCETAB:"idDispESRAAPSRDocTable",
		S4DISREJBTN:"idS4_Ftr_btnReject",
		S4DISRRASTATTXT:"idDispPSRStatusTxt",
		S4RRADETERMINSPECTAB:"idDispSysSpecDetermineTable",
		S4RRACCTAB:"idDispPSRRACbnCpyTable",
		S4DISPRRADISMADATRD:"idDispPSRRARdBtnGrp",
		S4DISPRRABRRALVLSELKEY:"idDispRRAssesComBx",
		S4DISPRRASRRALVLSELKEY:"idDispSRRAssesComBx",
		S4DISPRRABRRAASSESTXTAREA:"idDisp_RRAssesTxtArea",
		S4DISMSGPOPOVERBTN:"idDispRRAMessagePopover",
		S4DISESAVERCOMBOX:"id_Disp_Esa_VerComBx",
		S4DISESARESATCHTAB:"idDispEsaAttachTable",
		S4DISRRASUBFORAPPBTN:"idDispRRASFAppBtn",
		S4DISRRAMAINCOMMTEXTAREA:"idDispRRAMainComtTxtArea",
		S4DISRRAMAINCOMMTAB:"idDispPSRRRAMainCommTab",
		S4DISRRAMAINCOMMSAVEBTN:"idS4DispPSRRRaMainComSaveBtn",
		S4DISRRACCTAB:"idDispPSRRACbnCpyTable",
		S4DISGENINFOMINCOMMSAVBTN:"idS4_Disp_Gen_MainComSaveBtn",
		S4DISGENINFOMINCOMTXTAREA:"idS4_Disp_Gen_MainComtTxtArea",
		S4DISGENINFOMINCOMTTAB:"idS4_Disp_Gen_MainCommTab",
		S4DISESATAMBALBL:"IdS4DispEsaTAMBALbl",
		S4DISESAMASAGRLBL:"IdS4DispEsaMasAgrLbl",
		S4DISESACTAVPALBL:"IdS4DispEsaCTAVPALbl",
		S4DISESAMINCOMMSAVBTN:"idDispS2EsaMainComSaveBtn",
		S4DISESAMINCOMTXTAREA:"idDispEsaMainComtTxtArea",
		S4DISESAMINCOMTTAB:"idDispEsaMainCommTab",
		S4DISESAMASAGRRD:"idS4DispESA_MasAgrRbg",
		S4DISESACTAVPARD:"idS4DispESA_CTAVPARbg",
		S4DISESAPRHVMRD:"idDispEasPrHVMRdBtnGrp",
		S4DISESARFERD:"idDispEasRfeRdBtnGrp",
		S4DISESAEQUIPTYPRD:"idDispEasEquipTypeRdBtnGrp",
		S4DISESAEQUIPSAL1RD:"idDispEasEquipSel1RdBtnGrp",
		S4DISESAASPECRD:"idDispEasASpecRdBtnGrp",
		S4DISESASEVALRD:"idDispEasSEvalRdBtnGrp",
		S4DISESASEVAL2RD:"idDispEasSEval2RdBtnGrp",
		S4DISESAPRCURRRD:"idDispEasPrCurrRdBtnGrp",
		S4DISESAOUTBNDSHPCSTRD:"idDispEasOutbndShipCstRdBtnGrp",
		S4DISESAEQUIPRTNRD:"idDispEasEqupRtnRdBtnGrp",
		S4DISESAPYSTNDTRMRD:"idDispEasPTStndTermRdBtnGrp",
		S4DISESAPTEXPTRD:"idDispEasPTExceptRdBtnGrp",
		S4DISESACHINCONRD:"idDispEasChinConRdBtnGrp",
		S4DISESAROLRD:"idDispEasROLRdBtnGrp",
		S4DISESASHPTRMRD:"idDispEasShpTrmRdBtnGrp",
		S4DISESASPSHIPCONRD:"idDispEasSpShipConRdBtnGrp",
		S4DISESAPAYTRMPTCODEIP:"idS4DispESA_PayTrmPTCodeIP",		
		S4DISESAPREAGREEIP:"idS4DispESA_PreAgreeIP",
		S4DISESATAMBAIP:"idS4DispESATAMBAIP",
		S4DISESARES4EVALOTHIP:"idS4DispESA_ResForEvalOthIP",
		S4DISESAEQUIPAGREEIP:"idS4DispESA_EqipAgreeIP",
		S4DISESAEQUIPSOFTOTHSELIP:"idS4DispESA_EqipSoftOthSelIP",
		S4DISESAEQUIPSEL1PRIP:"idS4DispESA_EqipSel1PRIP",
		S4DISESAEVALTSNDACAGRIP:"idS4DispESA_EvalTsNDACAgreeIP",
		S4DISESAEVALTSNDDATIP:"idS4DispESA_EvalTsNDDatIP",
		S4DISESAPCRTSALPRCIP:"idS4DispESA_PrcTSalPrcIP",
		S4DISESAPRCBSALPRCIP:"idS4DispESA_PrcBSalPrcIP",
		S4DISESAPRCCOMBSALPRCIP:"idS4DispESA_PrcComBSalPrcIP",
		S4DISESAPRCEPSIP:"idS4DispESA_PrcEVAIP",
		S4DISESAPRCVPSIP:"idS4DispESA_PrcVPSIP",
		S4DISESAPRCEXSALPRCHVMIP:"idS4DispESA_PrcExSalPrcHVMIP",
		S4DISESAPRCGRSMARTARIP:"idS4DispESA_PrcGrsMarTarIP",
		S4DISESAPRCGRSMARBOTIP:"idS4DispESA_PrcGrsMarBotIP",
		S4DISESAPRCJUSTIP:"idS4DispESA_PrcJustIP",
		S4DISESASHPSTPROTRMIP:"idS4DispESA_ShpSTProTermIP",
		S4DISESASHPSTDESIP:"idS4DispESA_ShpSTDesIP",
		S4DISESASHPSTJUSTIP:"idS4DispESA_ShpSTJustIP",
		S4DISESASHPSTCOMIP:"idS4DispESA_ShpSTComIP",
		S4DISESASHPSSRCLOCIP:"idS4DispESA_ShpSSRCLocIP",
		S4DISESASHPSSRCJUSTIP:"idS4DispESA_ShpSSRCJustIP",
		S4DISESASHPSSRCCOMMIP:"idS4DispESA_ShpSSRCCommIP",
		S4DISESAEQUIPRETNOTHIP:"idS4DispESA_EquipRetnOthIP",
		S4DISESASUPMONTHVALIP:"idS4DispESA_SupMonthValIP",
		S4DISESASUPEXMONTHVALIP:"idS4DispESA_SupExMonthValIP",
		S4DISESAPAYTRMEXOTHIP:"idS4DispESA_PayTrmExOthIP",
		S4DISESAPAYTRMJUSTIP:"idS4DispESA_PayTrmJustIP",
		S4DISESAPAYTRMCOMIP:"idS4DispESA_PayTrmComIP",
		S4DISESAPREAGREECKB:"idS4DispESA_PreAgreeCkb",
		S4DISESAEQUIPCKB:"idS4DispESA_EquipCkb",
		S4DISESAABTUPGRDCKB:"idS4DispESA_AbTUpgrCkb",
		S4DISESASUPRTCKB:"idS4DispESA_suprtCkb",		
		S4DISESASUPRTLBL1: "id_Disp_Esa_SuppLbl1",
		S4DISESASUPRTLBL2: "id_Disp_Esa_SuppLbl2",
		S4DISESAPAYTRMPTDESIP:"idS4DispESA_PayTrmPTDesIP",
		S4DISESAEVALTSNDACAGREEDP:"idS4DispESA_EvalTsNDACAgreeDP",
		S4DISESAECALTSNDENDDTDP:"idS4DispESA_EvalTsNDEndDtDP",
		S4DISESAEVALTSNDSTARTDTDP:"idS4DispESA_EvalTsNDStartDtDP",
		S4DISESAEVALNDESTSHIPDTDP:"idS4DispESA_EvalTsNDEstShipDtDP",
		S4DISCBCMEADOCTAB:"id_Disp_CBC_MEADoc_Table",
		S4DISCBCMEADOCCHOOSBTN:"id_Disp_CBC_MEADoc_ChooseBtn",
		S4DISCBCQUESTAB:"IdS4_Disp_CBC_QuesTable",
		S4DISCBCCCTAB:"id_DispCBCCbnCpyTable",
		S4DISCBCMAINCOMSAVEBTN:"idS4_DispCBCMainComSaveBtn",
		S4DISCBCMAINCOMTXTAREA:"id_DispCBCMainComtTxtArea",
		S4DISCBCMAINCOMTAB:"id_DispCBCMainCommTab",
		S4DISCARMMAINCOMSAVEBTN: "idS4_Carm_MainComSaveBtn",
		S4DISCARMATTAB: "idS4CarmAttTable",
		//***********End Of PCR026243 DL:1803 Display Migration to Q2C******************
		//***********Start PCR033306: Q2C Display Enhancements**************************
		S4DISESADTBTN : "idDispEsaEditBtn",
		S1_DFTNO_SEARCH : "idS1_OPP_IP_DFTN",
		S4DISESA_CRBNCPY_TBL : "idDispEsaCbnCpyTable",
		S4DISESA_CRBNCPY_LBL : "idDispS4_Esa_LB_CbnCpyText",
		S4DISESA_CRBNCPY_INP : "idDispS4_Esa_IP_CbnCpy",
		S4DISESA_CC_PNL : "idDispEsaCbnCpyPnl",
		S4DISESA_EXT_BTN : "idDispEsaReqExtBtn",
		S4DISESA_CHKLST_BTN : "idDispEsaCheckListBtn",
		S4DISESA_IDS_PANL_BT_CARBON_COPY_BOX : "idDispS4_Esa_BT_CbnCpyBox",
		S4DISESA_EQIPSEL1OTHIP : "idS4DispESA_EqipSel1OthIP",
		S4DISESA_PTSTNDTRMIP : "idS4DispESA_PTStndTermIP",
		//***********End Of PCR033306: Q2C Display Enhancements*************************
		//***********Start PCR034716: Q2C ESA,PSR Enhancements**************************
		S2ESA_PANL_CHKLST_COMMENT_SAVEBTN : "idS2EsaChkLstComSaveBtn",
		S2ESA_PANL_CHKLST_COMMENT_TEXT_AREA : "idEsaChkLstComtTxtArea",
		S2ESA_PANL_CHKLST_COMMENT_COMMTABLE : "idEsaChkLstCommTab",
		S2FTER_BTN_PSR_RRA_RESET : "idS2_Ftr_btnPsrRraReset",
		S2ESAEQUIPSMRTEVALCHKBOX : "idEasEquipSelUrsCkb",
		S2ESAEVAL23RDDESIP : "idEasSEval23RDDesIP"
		//***********End Of PCR034716: Q2C ESA,PSR Enhancements*************************
};


com.amat.crm.opportunity.StandardSAPIcons = {
		
		ICON_SAP_REFRESH : "sap-icon://refresh",
		ICON_SAP_SAVE : "sap-icon://save",
		ICON_SAP_MSG_SUCCESS : "sap-icon://message-success",
		ICON_SAP_SLIM_ARROW_DOWN : "sap-icon://slim-arrow-down",
		ICON_SAP_SLIM_ARROW_UP : "sap-icon://slim-arrow-up",
		ICON_SAP_MSG_ERROR : "sap-icon://message-error",
		ICON_SAP_MSG_WARNING :"sap-icon://message-warning",
		ICON_SAP_DELETE :"sap-icon://delete",
		ICON_SAP_ADD :"sap-icon://add",
		ICON_SAP_ATTACHMENT :"sap-icon://attachment",
		ICON_SAP_CANCEL_2 :"sap-icon://sys-cancel-2"
};

com.amat.crm.opportunity.Elements = {
	
		BUTTON_CREATE_SALES_ORDER : "CreateSalesOrderButton",
		BUTTON_ADD_WF : "AddPartButton",
		BUTTON_OPP_LIST : "serviceOrderPartsButton"
};